"""Add offer field to Order

Revision ID: 487ea35acddf
Revises: a508cd81f895
Create Date: 2025-06-30 14:14:31.081365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487ea35acddf'
down_revision = 'a508cd81f895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('offer')

    # ### end Alembic commands ###
